name: Bitcoin Bot CI

on:
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install bit requests

      - name: Restore State
        uses: actions/cache@v3
        with:
          path: bot_state.txt
          key: bot-state-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            bot-state-

      - name: Run Bot
        env:
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          CUSTODY_ADDRESS: ${{ secrets.CUSTODY_ADDRESS }}
        run: python bitcoin_bot.py

      - name: Save State
        if: always()
        uses: actions/cache@v3
        with:
          path: bot_state.txt
          key: bot-state-${{ github.run_id }}-${{ github.run_attempt }}
